name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/docker-container

env:
  IMAGE_NAME: frontend-website-mr
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: false
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        if: false
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        if: false
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/standalonealliance/${{ env.IMAGE_NAME }}:latest

      - name: Dispatch k8s deploy
        shell: bash
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/antoniogisondi/front-end-website-mr/dispatches \
          -d '{"event_type":"kubernetes_deployment"}'
